# Generated by Django 3.1.5 on 2021-04-08 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210327_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='parents',
            new_name='parent',
        ),
    ]
